#include <stdio.h>

void main() {
  int opcao;
  float animação_um,animação_dois,animação_tres;
  printf("selecione a sua animação:\n");
  printf("[1] passarinho dançarino\n");
  printf("[2] Homen correndo\n");
  printf("[3] Moeda\n");
    scanf("%d", &opcao);
    if(opcao == 1){



      while(1){
          printf(" .c:'.,cl,.'l:',,;;'......cO;                     \n");
          printf(" do;';oxoc;:l;;llllc'.';;'.,;.                    \n");
          printf(" c..ckkkkkkkd,;llllc'.:kkd;.':c.                  \n");
          printf(" '.,okkkkkkkkc;lllll,.:kkkdl,cO;                  \n");
          printf(" ..;xkkkkkkkkc,ccll:,;okkkkk:,co,                 \n");
          printf(" ..,dkkkkkkkkc..,;,'ckkkkkkkc;ll.                 \n");
          printf(" ..'okkkkkkkko,....'okkkkkkkc,:c.                \n");
          printf(" c..ckkkkkkkkkdl;,:okkkkkkkkd,.',';.              \n");
          printf(" d..':lxkkkkkkkkxxkkkkkkkkkkkdoc;,;'..'.,.       \n");
          printf(" o...'';llllldkkkkkkkkkkkkkkkkkkdll;..'cdo.      \n");
          printf(" o..,l;'''''';dkkkkkkkkkkkkkkkkkkkkdlc,..;lc.     \n");
          printf(" o..;lc;;;;;;,,;clllllllllllllllllllllc'..,:c.   \n");
          printf(" o..........................................;'      \n");
          usleep(100000);
          system("clear");

          printf("                                                 \n");
          printf("           .,,,,,,,,,.                            \n");
          printf("         .ckKxodooxOOdcc.                         \n");
          printf("      .cclooc'....';;cool.                        \n");
          printf("     .loc;;;;clllllc;;;;;:;,.                     \n");
          printf("   .c:'.,okd;;cdo:::::cl,..oc                     \n");
          printf("  .:o;';okkx;';;,';::;'....,:,.                   \n");
          printf("  co..ckkkkkddkc,cclll;.,c:,:o:.                  \n");
          printf("  co..ckkkkkkkk:,cllll;.:kkd,.':c.                \n");
          printf(".,:;.,okkkkkkkk:,cclll;.ckkkdl;;o:.               \n");
          printf("cNo..ckkkkkkkkko,.;loc,.ckkkkkc..oc               \n");
          printf(",dd;.:kkkkkkkkkx;..;:,.'lkkkkko,.:,               \n");
          printf("  ;:.ckkkkkkkkkkc.....;ldkkkkkk:.,'               \n");
          printf(",dc..'okkkkkkkkkxoc;;cxkkkkkkkkc..,;,.            \n");
          printf("kNo..':lllllldkkkkkkkkkkkkkkkkkdcc,.;l.           \n");
          printf("KOc,c;''''''';lldkkkkkkkkkkkkkkkkkc..;lc.         \n");
          printf("xx:':;;;;,.,,...,;;cllllllllllllllc;'.;od,        \n");
          printf("cNo.....................................oc         \n");
          usleep(100000);
          system("clear");

          printf("                                                 \n");
          printf("                                                 \n");
          printf("                   .ccccccc.                      \n");
          printf("               .ccckNKOOOOkdcc.                   \n");
          printf("            .;;cc:ccccccc:,:c::,,.                \n");
          printf("         .c;:;.,cccllxOOOxlllc,;ol.               \n");
          printf("        .lkc,coxo:;oOOxooooooo;..:,               \n");
          printf("      .cdc.,dOOOc..cOd,.',,;'....':l.             \n");
          printf("      cNx'.lOOOOxlldOc..;lll;.....cO;             \n");
          printf("     ,do;,:dOOOOOOOOOl'':lll;..:d:''c,            \n");
          printf("     co..lOOOOOOOOOOOl'':lll;.'lOd,.cd.           \n");
          printf("     co.'dOOOOOOOOOOOo,.;llc,.,dOOc..dc           \n");
          printf("     co..lOOOOOOOOOOOOc.';:,..cOOOl..oc           \n");
          printf("   .,:;.'::lxOOOOOOOOOo:'...,:oOOOc.'dc           \n");
          printf("   ;Oc..cl'':lldOOOOOOOOdcclxOOOOx,.cd.           \n");
          printf("  .:;';lxl''''':lldOOOOOOOOOOOOOOc..oc            \n");
          printf(" ,dl,.'cooc:::,....,::coooooooooooc'.c:            \n");
          printf(" cNo.................................oc           \n");
          usleep(100000);
          system("clear");

          printf("           .ccccccc.\n");
          printf("      .,,,;cooolccoo;;,,.\n");
          printf("     .dOx;..;lllll;..;xOd.\n");
          printf("   .cdo;',loOXXXXXkll;';odc.\n");
          printf("  ,ol:;c,':oko:cccccc,...ckl.\n");
          printf("  ;c.;kXo..::..;c::'.......oc\n");
          printf(",dc..oXX0kk0o.':lll;..cxxc.,ld,\n");
          printf("kNo.'oXXXXXXo',:lll;..oXXOo;cOd.\n");
          printf("KOc;oOXXXXXXo.':lol;..dXXXXl';xc\n");
          printf("Ol,:k0XXXXXX0c.,clc'.:0XXXXx,.oc\n");
          printf("KOc;dOXXXXXXXl..';'..lXXXXXo..oc\n");
          printf("dNo..oXXXXXXXOx:..'lxOXXXXXk,.:; ..\n");
          printf("cNo..lXXXXXXXXXOolkXXXXXXXXXkl,..;:';.\n");
          printf(".,;'.,dkkkkk0XXXXXXXXXXXXXXXXXOxxl;,;,;l:.\n");
          printf("  ;c.;:''''':doOXXXXXXXXXXXXXXXXXXOdo;';clc.\n");
          printf("  ;c.lOdood:'''oXXXXXXXXXXXXXXXXXXXXXk,..;ol.\n");
          printf("  ';.:xxxxxocccoxxxxxxxxxxxxxxxxxxxxxxl::'.';;.\n");
          printf("  ';........................................;l'\n");
          usleep(100000);
          system("clear");

          printf("                                                 \n");
          printf("        .;:;;,.,;;::,.                            \n");
          printf("     .;':;........'co:.                           \n");
          printf("   .clc;'':cllllc::,.':c.                         \n");
          printf("  .lo;;o:coxdllllllc;''::,,.                      \n");
          printf(" .c:'.,cl,.'l:',,;;'......cO;                     \n");
          printf(" do;';oxoc;:l;;llllc'.';;'.,;.                    \n");
          printf(" c..ckkkkkkkd,;llllc'.:kkd;.':c.                  \n");
          printf(" '.,okkkkkkkkc;lllll,.:kkkdl,cO;                  \n");
          printf(" ..;xkkkkkkkkc,ccll:,;okkkkk:,co,                 \n");
          printf(" ..,dkkkkkkkkc..,;,'ckkkkkkkc;ll.                 \n");
          printf(" ..'okkkkkkkko,....'okkkkkkkc,:c.                \n");
          printf(" c..ckkkkkkkkkdl;,:okkkkkkkkd,.',';.              \n");
          printf(" d..':lxkkkkkkkkxxkkkkkkkkkkkdoc;,;'..'.,.       \n");
          printf(" o...'';llllldkkkkkkkkkkkkkkkkkkdll;..'cdo.      \n");
          printf(" o..,l;'''''';dkkkkkkkkkkkkkkkkkkkkdlc,..;lc.     \n");
          printf(" o..;lc;;;;;;,,;clllllllllllllllllllllc'..,:c.   \n");
          printf(" o..........................................;'      \n");
          usleep(100000);
          system("clear");

          printf("                                                 \n");
          printf("           .,,,,,,,,,.                            \n");
          printf("         .ckKxodooxOOdcc.                         \n");
          printf("      .cclooc'....';;cool.                        \n");
          printf("     .loc;;;;clllllc;;;;;:;,.                     \n");
          printf("   .c:'.,okd;;cdo:::::cl,..oc                     \n");
          printf("  .:o;';okkx;';;,';::;'....,:,.                   \n");
          printf("  co..ckkkkkddkc,cclll;.,c:,:o:.                  \n");
          printf("  co..ckkkkkkkk:,cllll;.:kkd,.':c.                \n");
          printf(".,:;.,okkkkkkkk:,cclll;.ckkkdl;;o:.               \n");
          printf("cNo..ckkkkkkkkko,.;loc,.ckkkkkc..oc               \n");
          printf(",dd;.:kkkkkkkkkx;..;:,.'lkkkkko,.:,               \n");
          printf("  ;:.ckkkkkkkkkkc.....;ldkkkkkk:.,'               \n");
          printf(",dc..'okkkkkkkkkxoc;;cxkkkkkkkkc..,;,.            \n");
          printf("kNo..':lllllldkkkkkkkkkkkkkkkkkdcc,.;l.           \n");
          printf("KOc,c;''''''';lldkkkkkkkkkkkkkkkkkc..;lc.         \n");
          printf("xx:':;;;;,.,,...,;;cllllllllllllllc;'.;od,        \n");
          printf("cNo.....................................oc         \n");
          usleep(100000);
          system("clear");

         printf("                                                 \n");
         printf("                                                 \n");
         printf("                   .ccccccc.                      \n");
         printf("               .ccckNKOOOOkdcc.                   \n");
         printf("            .;;cc:ccccccc:,:c::,,.                \n");
         printf("         .c;:;.,cccllxOOOxlllc,;ol.               \n");
         printf("        .lkc,coxo:;oOOxooooooo;..:,               \n");
         printf("      .cdc.,dOOOc..cOd,.',,;'....':l.             \n");
         printf("      cNx'.lOOOOxlldOc..;lll;.....cO;             \n");
         printf("     ,do;,:dOOOOOOOOOl'':lll;..:d:''c,            \n");
         printf("     co..lOOOOOOOOOOOl'':lll;.'lOd,.cd.           \n");
         printf("     co.'dOOOOOOOOOOOo,.;llc,.,dOOc..dc           \n");
         printf("     co..lOOOOOOOOOOOOc.';:,..cOOOl..oc           \n");
         printf("   .,:;.'::lxOOOOOOOOOo:'...,:oOOOc.'dc           \n");
         printf("   ;Oc..cl'':lldOOOOOOOOdcclxOOOOx,.cd.           \n");
         printf("  .:;';lxl''''':lldOOOOOOOOOOOOOOc..oc            \n");
         printf(" ,dl,.'cooc:::,....,::coooooooooooc'.c:            \n");
         printf(" cNo.................................oc           \n");
         usleep(100000);
         system("clear");

         printf("                                                 \n");
         printf("                                                 \n");
         printf("                                                 \n");
         printf("                        .cccccccc.                \n");
         printf("                  .,,,;;cc:cccccc:;;,.            \n");
         printf("                .cdxo;..,::cccc::,..;l.           \n");
         printf("               ,do:,,:c:coxxdllll:;,';:,.         \n");
         printf("             .cl;.,oxxc'.,cc,.';;;'...oNc         \n");
         printf("             ;Oc..cxxxc'.,c;..;lll;...cO;         \n");
         printf("           .;;',:ldxxxdoldxc..;lll:'...'c,        \n");
         printf("           ;c..cxxxxkxxkxxxc'.;lll:'','.cdc.      \n");
         printf("         .c;.;odxxxxxxxxxxxd;.,cll;.,l:.'dNc      \n");
         printf("        .:,''ccoxkxxkxxxxxxx:..,:;'.:xc..oNc      \n");
         printf("      .lc,.'lc':dxxxkxxxxxxxol,...',lx:..dNc      \n");
         printf("     .:,',coxoc;;ccccoxxxxxxxxo:::oxxo,.cdc.      \n");
         printf("  .;':;.'oxxxxxc''''';cccoxxxxxxxxxxxc..oc        \n");
         printf(",do:'..,:llllll:;;;;;;,..,;:lllllllll;..oc        \n");
         printf("cNo.....................................oc         \n");
         usleep(100000);
         system("clear");

         printf("                                                 \n");
         printf("                                                 \n");
         printf("                              .ccccc.             \n");
         printf("                         .cc;'coooxkl;.           \n");
         printf("                     .:c:::c:,,,,,;c;;,.'.        \n");
         printf("                   .clc,',:,..:xxocc;'..c;        \n");
         printf("                  .c:,';:ox:..:c,,,,,,...cd,      \n");
         printf("                .c:'.,oxxxxl::l:.,loll;..;ol.     \n");
         printf("                ;Oc..:xxxxxxxxx:.,llll,....oc     \n");
         printf("             .,;,',:loxxxxxxxxx:.,llll;.,,.'ld,   \n");
         printf("            .lo;..:xxxxxxxxxxxx:.'cllc,.:l:'cO;   \n");
         printf("           .:;...'cxxxxxxxxxxxxoc;,::,..cdl;;l'   \n");
         printf("         .cl;':,'';oxxxxxxdxxxxxx:....,cooc,cO;   \n");
         printf("     .,,,::;,lxoc:,,:lxxxxxxxxxxxo:,,;lxxl;'oNc   \n");
         printf("   .cdxo;':lxxxxxxc'';cccccoxxxxxxxxxxxxo,.;lc.   \n");
         printf("  .loc'.'lxxxxxxxxocc;''''';ccoxxxxxxxxx:..oc     \n");
         printf("olc,..',:cccccccccccc:;;;;;;;;:ccccccccc,.'c,     \n");
         printf("Ol;......................................;l'       \n");
         usleep(100000);
         system("clear");

         printf("                                                 \n");
         printf("                              ,ddoodd,            \n");
         printf("                         .cc' ,ooccoo,'cc.        \n");
         printf("                      .ccldo;...',,...;oxdc.      \n");
         printf("                   .,,:cc;.,'..;lol;;,'..lkl.     \n");
         printf("                  .dOc';:ccl;..;dl,.''.....oc     \n");
         printf("                .,lc',cdddddlccld;.,;c::'..,cc:.  \n");
         printf("                cNo..:ddddddddddd;':clll;,c,';xc  \n");
         printf("               .lo;,clddddddddddd;':clll;:kc..;'  \n");
         printf("             .,c;..:ddddddddddddd:';clll,;ll,..   \n");
         printf("             ;Oc..';:ldddddddddddl,.,c:;';dd;..   \n");
         printf("           .''',:c:,'cdddddddddddo:,''..'cdd;..   \n");
         printf("         .cdc';lddd:';lddddddddddddd;.';lddl,..   \n");
         printf("      .,;::;,cdddddol;;lllllodddddddlcldddd:.'l;  \n");
         printf("     .dOc..,lddddddddlcc:;'';cclddddddddddd;;ll.  \n");
         printf("   .coc,;::ldddddddddddddlcccc:ldddddddddl:,cO;   \n");
         printf(" ,xl::,..,cccccccccccccccccccccccccccccccc:;':xx,\n");
         printf("cNd.........................................;lOc   \n");
         usleep(100000);
         system("clear");}
        }

      if(opcao==2){

        while(1){
        printf("                     .,;lkOx,           \n");
        printf("                     .,,cxkd'           \n");
        printf("                     ,c;cccl'           \n");
        printf("                   ..',:ol;.            \n");
        printf("                  .....,lko.            \n");
        printf("                '::'..,,;dxl.           \n");
        printf("             .';:;,'..,:;:dxl:,.....    \n");
        printf("             ,c,:c:,..,::;:odddoooddl.  \n");
        printf("              .;:oc,'':llclddd:',,cko.  \n");
        printf("               ';::,,:dkdl:,,,.   .,.   \n");
        printf("               ':',;:oOOdo:..           \n");
        printf("               :d,,:clddk00Odc,         \n");
        printf("               ,l,;:ccc:coxk00Od:,      \n");
        printf("              .;;;:cccc;.,::cldxxd,     \n");
        printf("             .:;,::ccc,   ,:;;;cdd'     \n");
        printf("        ..,,,cc;;::;,.       .,lxd'     \n");
        printf(" ..,c:,;ccclooc::c,          .,:od,     \n");
        printf(":dxoc:;;;;;;:cc;'.           ';,co'     \n");
        printf("ldoc:;''',.....              .',cd,     \n");
        printf("lll;.                         .;cxd,..  \n");
        printf("cl;.                          .:;cddddl.\n");
        printf("::.                            .,,,,,,' \n");

        usleep(100000);
        system("clear");

        printf("                       .''''.           \n");
        printf("                      .:clxx:           \n");
        printf("                      .;,lOOd'          \n");
        printf("                      .;,cllo'          \n");
        printf("                    .';:ll:::.          \n");
        printf("                   .c;':xxo,            \n");
        printf("                  .''.,dOxo;            \n");
        printf("                  ,,..;xxoll'           \n");
        printf("                 ;:'..:xxlcl'           \n");
        printf("                .:;'.';cddd:.           \n");
        printf("                 .;,,;llcldxo:,.        \n");
        printf("                .;;;:oOOo;:lddxxl.      \n");
        printf("                .;',:lOOd;.':looo'      \n");
        printf("                .,'',;okkx:  ',,'.      \n");
        printf("         ....    .,'.,:oxkkc.           \n");
        printf("       ,ldxkxl;'..,;'',cokOk:           \n");
        printf("     .clccccc::cllool:;:lldkx;          \n");
        printf("    .;,'.....,:c;::llllclccodx;         \n");
        printf("              ...'.,;;::cccol:.         \n");
        printf("                    ..';::odo'          \n");
        printf("                       'c;clo'          \n");
        printf("                       'c;:lc.          \n");
        printf("                       'l:cd,           \n");
        printf("                       'lcoxo,          \n");
        printf("                       'lccoddl:.       \n");
        printf("                       ,ollloooc.       \n");

        usleep(100000);
        system("clear");

        printf("                        .''.            \n");
        printf("                      .;,lxo,           \n");
        printf("                      .,,lOOx'          \n");
        printf("                      .;,:ooo'          \n");
        printf("                   .'';:cl:,:.          \n");
        printf("                   'l:;oxol'            \n");
        printf("                  .,,:dkdoo;            \n");
        printf("                  'cldxlclll'           \n");
        printf("                .ccokko:ccc:.           \n");
        printf("                .;::coxoccl'            \n");
        printf("                 .;,';lxolx;            \n");
        printf("                .;;;:codddoc:,          \n");
        printf("                .;',:lkkddoclo:.        \n");
        printf("                .''.',:oddol:;:.        \n");
        printf("             ..  .,'..';coxx:           \n");
        printf("            :dxo:,,;,,,,,:oxxl.         \n");
        printf("          .lodddlcc:::ccclloxxo.        \n");
        printf("         .colll:'.,:;;;;:cccldd,        \n");
        printf("          ;oc'.   .loc:;::ccc:,.        \n");
        printf("           .      ;c:cllll;..           \n");
        printf("                 'l:;cll,               \n");
        printf("                .cc::cc,                \n");
        printf("                'l::llc.                \n");
        printf("               .cllodd,                 \n");
        printf("               'lccoddl:;.              \n");
        printf("               'l:;:clodd,              \n");

        usleep(100000);
        system("clear");

        printf("                      ';''',.           \n");
        printf("                      'ccdkk:           \n");
        printf("                     .,';dOko.          \n");
        printf("                     .;;:cclc.          \n");
        printf("                    .;lcolc;.           \n");
        printf("                  ':cldxdod,            \n");
        printf("                ':oxkxoccoo;            \n");
        printf("              .:cdxlc:;:clld,           \n");
        printf("               ';dk:'',:ccc;.           \n");
        printf("               .,:do;,;clcll,..         \n");
        printf("                .,cooloxdccclcc;;:.     \n");
        printf("                .,,cdxOOdl:,,;::cl'     \n");
        printf("                .,';cokkOOko::'...      \n");
        printf("                ':'',,;:coxkOko,.       \n");
        printf("                'c,;ccc:;,;:ldkkxo.     \n");
        printf("                'c,:lodolc::codddd,     \n");
        printf("                'c,:clllc:::ccc:::.     \n");
        printf("               .llccc::;;;::,'...       \n");
        printf("              ':lloolccl:...            \n");
        printf("            .:cclloooo;.                \n");
        printf("           .:c;:ccodd:                  \n");
        printf("          'cc::c:;;;:.                  \n");
        printf("        'colllc'                        \n");
        printf("        ;lclod,                         \n");
        printf("         .:odx:.                        \n");
        printf("          'ooddx,                       \n");

        usleep(100000);
        system("clear");

        printf("                       ;lo:.            \n");
        printf("                      .;lkOo.           \n");
        printf("                     .,':xkxc.          \n");
        printf("                     ,l;cc:ld,          \n");
        printf("                  ...;lool,.            \n");
        printf("                .:ldoddood;             \n");
        printf("             .,:oddlc:;;ldo'            \n");
        printf("             .;okd:,.';:ccc'            \n");
        printf("             ,c:xkl,.',:ccc:;'..,;:,    \n");
        printf("             .;:okc''':llc;,;;:;,;:o,   \n");
        printf("               ,ldl,,:dkdc;'....,,:;.   \n");
        printf("               .cdo::lkOxdl,.           \n");
        printf("               ;dcc;;:lodxkOkdc,.       \n");
        printf("               :o,,,,,,,;;:loxkkko:.    \n");
        printf("               ';;cllc:,.';,,;;cdxd,    \n");
        printf("              ':;:clcc,   ..::;cdo:.    \n");
        printf("            .,:;;:c:,'     'l::loo'     \n");
        printf("         ';cooc;::;.      .cc;:co:.      \n");
        printf("       'clccllc:;.        ;l:;:l;       \n");
        printf("    .,clc:;:c;;'         :ol::ll.       \n");
        printf("  .coolccc:,'           'oollod:        \n");
        printf("  .:clloc'              .coooxxxl,.     \n");
        printf("   'lod:                  .,cddddd,     \n");
        printf("   .cod,                     .....      \n");
        printf("     ..                                  \n");

        usleep(100000);
        system("clear");

        printf("                      ;xc::.            \n");
        printf("                     .,;lkOo.           \n");
        printf("                     .,'cxkd,           \n");
        printf("                     'c;cc:l'           \n");
        printf("                ...',:ldoc;,.           \n");
        printf("               'cdddoodood:             \n");
        printf("             .:oddoc:;;:ldo'            \n");
        printf("             .:dko:'.';:ccc'     .'.    \n");
        printf("             .:lkxc,.',:ccc;,,,',col.   \n");
        printf("              ':dxl,.':llc;,;;::;;::.   \n");
        printf("               'odc,;:dkdl,........     \n");
        printf("               .odc;cokOxdl,.           \n");
        printf("               .::,,;;coxkOOko,.        \n");
        printf("               .:,;,,,,,;:codkkko:,     \n");
        printf("              .:;:clccc;,:;;;:coxxx,    \n");
        printf("             'l:;:ccc:'. .,:':c;lxd'    \n");
        printf("      ..,;,;;cc;:cc;'.       ;l;lxd'    \n");
        printf(" ,clc;cl::clol:;:l;          .;,:oo'    \n");
        printf(".loooc::;;;c;...''            .,;cl'    \n");
        printf("'llll:;;.....                 .'':l'    \n");
        printf(":lo;.                          .,;o:.   \n");
        printf(":ol.                           .;;oxdc;,\n");
        printf(" ..                             ':coooc; \n");
        printf("                                 .....   \n");

        usleep(100000);
        system("clear");

        printf("                      .':xc.            \n");
        printf("                     .:ccxOd'           \n");
        printf("                     ,l';dOxo'          \n");
        printf("                      ';:ccll.          \n");
        printf("                  .,,:clol,'.           \n");
        printf("                 'lddddxdoc.            \n");
        printf("               'codxkdc:cdo;.           \n");
        printf("              'loxd:,,;:cclc.           \n");
        printf("              'ccxx;.',:ccc;.           \n");
        printf("              .;:ld:'';llccol;;,;:,.    \n");
        printf("               .;col:cdkdc:ccc:;:cl.    \n");
        printf("                'ccdxxOOdoc....,,.      \n");
        printf("                .;:ododkOOx:            \n");
        printf("                .:,,,,,:oxOOo,          \n");
        printf("      ..        'c;:cc:,,;cdkko'        \n");
        printf("    'ldxl,......;:;cooooc;;;cdkd:.      \n");
        printf("   ;olodolcccloxdc;cllo:..',;:oxd'      \n");
        printf(" .clloc,,:c:;;:loc:clld;   ,l;lxd,      \n");
        printf(" .;,''.  .....'.',;:cl:.   'c;cdd,      \n");
        printf("                 .....     'l;:lo'      \n");
        printf("                           .;:;:l'      \n");
        printf("                            .:;:l:.     \n");
        printf("                             .::oxl'.   \n");
        printf("                             'c:oxxool. \n");
        printf("                             .,,,;;;;,   \n");

        usleep(100000);
        system("clear");

        printf("                      .''''.           \n");
        printf("                      .cclxx:           \n");
        printf("                      .;,lOOd'          \n");
        printf("                      .;,cllo'          \n");
        printf("                    .';cll:::.          \n");
        printf("                   ,c:cdxol;            \n");
        printf("                  ;lcokxooo;            \n");
        printf("                 ;loxxocclll'           \n");
        printf("                'ccxOd::cccl'           \n");
        printf("                .::ldxocccl'            \n");
        printf("                 ':,,cdxold:..          \n");
        printf("                .;,;:coxdllllol.        \n");
        printf("                .;';:lodxxoc:cll.       \n");
        printf("                .,'.',:llod;';'.        \n");
        printf("         ,::,.   .:'..';cdxo.           \n");
        printf("      .,looxxl;;;';:,'',;cdxl.          \n");
        printf("     .:ollc:cc::cloooc;;;;cdd:.         \n");
        printf("     .:,,.. .';;:,;clc:cc:;cdd,         \n");
        printf("               ..';;c:;;cc:loo'         \n");
        printf("                    ..':c::oo;          \n");
        printf("                       'c;:ll'          \n");
        printf("                       'c;;co'          \n");
        printf("                       .c:;co,          \n");
        printf("                       'l::od:          \n");
        printf("                       'lcldxdc:.       \n");
        printf("                       'lcloddod,       \n");

        usleep(100000);
        system("clear");

        printf("                        .''.            \n");
        printf("                      .;,lxo,           \n");
        printf("                      .,,lOOx'          \n");
        printf("                      .;,:ooo'          \n");
        printf("                   ..,;:cl:,:.          \n");
        printf("                   'l:,cxdl'            \n");
        printf("                  .,'';xkdo;            \n");
        printf("                  .,''lkdlll'           \n");
        printf("                  ''.,okocc:.           \n");
        printf("                 .;'.':dxol'            \n");
        printf("                 .:,',:cldxo,.          \n");
        printf("                .;;;:lkklcodxoc.        \n");
        printf("                .;';:oOOdooloddl.       \n");
        printf("                .''',:okkxxl;coc.       \n");
        printf("             ... .,'.':oxOOo,.'.        \n");
        printf("            :dxxl::;'',coxOOx:          \n");
        printf("          .looodolc;,'':lloxkx:.        \n");
        printf("         .coooc,,,',c:,;cc:clol.        \n");
        printf("          ';;'     .:c;;cl:,'.          \n");
        printf("                  ':cccll:.             \n");
        printf("                 'l:;:cll'              \n");
        printf("                 ;c;;:co;               \n");
        printf("                'l;;;:l:                \n");
        printf("               .cc;:ll:.                \n");
        printf("               'lcldxdol;               \n");
        printf("               'lcldxxdool.             \n");

        usleep(100000);
        system("clear");

        printf("                   ';''',.           \n");
        printf("                      'ccdkx:           \n");
        printf("                     .,';dOko'          \n");
        printf("                      .,;cclc.          \n");
        printf("                    ..':llc;.           \n");
        printf("                   .,'';dxo.            \n");
        printf("                 .,,..';xko;            \n");
        printf("                .c;'..';dxlo,           \n");
        printf("               .';;'..',lxxxo,          \n");
        printf("               ,c:l:'';::codxxo::,.     \n");
        printf("               .cc;;,;oxoc;;lloddxdc.   \n");
        printf("                ,c,;:oOOol;...';:lll'   \n");
        printf("                .;';:lkkkkxl:.   ..     \n");
        printf("                .;',:cddxO00Od:,        \n");
        printf("                ':',;:ll::coxOOko,      \n");
        printf("                .;',::clc::clooddc.     \n");
        printf("                ':';:ccc:;;::;::,.      \n");
        printf("               .lc,;:cc:::l:. ..        \n");
        printf("              'clc:::clc'.'.            \n");
        printf("            .ccccllll:'                 \n");
        printf("           .cc;:ccldd,                  \n");
        printf("          'cc;;::'...                   \n");
        printf("        ,loc;:lc.                       \n");
        printf("       'ooollo;                         \n");
        printf("        ,loxxd:..                       \n");
        printf("         ;oddddx,                        \n");

        usleep(100000);
        system("clear");

        printf("                     .:doc,.           \n");
        printf("                     .;:lkOk,           \n");
        printf("                     .;,cxkxc.          \n");
        printf("                     ,c;cc:ld,          \n");
        printf("                   .'',:ol,.            \n");
        printf("                  .''..,okl.            \n");
        printf("                 .,'..,,:xx;            \n");
        printf("              .,,,,'..,;;cxx:''..       \n");
        printf("              .;:c:'..,::;cdxxdddl::'   \n");
        printf("              '::oc,'':ll:ll:;c:cool;.  \n");
        printf("              .;:::,,:dkdl:'. .. ...    \n");
        printf("               .'',;:oOOdo;..           \n");
        printf("                .,,:clxxkOOOdc,         \n");
        printf("               .:,,:cclccoxk00Od:'      \n");
        printf("               ',,;:ccc;;c;;:coxxd'     \n");
        printf("              ':,;:ccc:..'':::loc:.     \n");
        printf("            .,:;;::cc,    ,l:coo:.      \n");
        printf("         ,;cool:::;..    .cc;:lc.       \n");
        printf("       'clcccll::;.      ;oc:lo'        \n");
        printf("   .,;cc::::cl:..       :oolod:         \n");
        printf(" .ldol:::c:,'..        ,olloxx:         \n");
        printf(" 'oddll:'.              ..:odxx:        \n");
        printf(" .codoc.                   ,;;::.       \n");
        printf("  .cooo'                                \n");
        printf("    ';:.                                \n");}

      }

  if(opcao==3){

  while(1){
    printf("~~~~~~~~~~~~^P@@@@@@@@@@@@@P^~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~7??????5GGGGGGGGGGGGG5??????7~~~~~~~~~~~~~~\n");
    printf("~~~~~^B@@@@@@?             7@@@@@@B^^~~~~~~~~~~~~\n");
    printf("~~7PPPJ??????~:::::::::::::!YYY5555PPP7~~~~~~~~~~\n");
    printf("~~?@@@!      :^^^^^^^^^^^^^^^^^!!!J@@@?~~~~~~~~~~\n");
    printf("~^?@@@!   ^^^::::       .:.:^^^!!!Y@@@Y777~~~~~~~\n");
    printf("???JGGG~...^^^:...   ....!!7~^^^~!!?BBB5Y5J!!!~~~~\n");
    printf("#@@G   :^^^:::.   ::::^^~&@@5.::^^^~!!!B@@#???!~~~\n");
    printf("#@@G   :^^^:::.   ::::^^~&@@5.::^^^~!!!B@@#???!~~~\n");
    printf("#@@G   :^^^:::.   ::::^^~&@@5.::^^^~!!!B@@#???!~~~\n");
    printf("#@@G   :^^^:::.   ::::^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("#@@G   :^^^:::.   ::::^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("#@@G   :^^^:::.   ::::^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("#@@G   :^^^:::.   ::::^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("#@@G   :^^^:::.   ::::^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("#@@G   :^^^:::.   .:::^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("#@@G   :^^^:::.   :::^^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("#@@G   :^^^:::.   ^^^^^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("#@@G   :^^^:::.   ^^^^^^~&@@5.::^^^~!!!B@@#???????\n");
    printf("B&@G...^^^^:::.  .~~~~~~!#&@5.::^^^~777B@@#???????\n");
    printf("!!!?&#&?^^^:::...^#&&&&&&~^^^^^^!!!J&&&5JJJ???????\n");
    printf("~^?@@@?^^^::::::^GGGGGGG^::^~~~!!!Y@@@Y??????????\n");
    printf("~~?@@@?^^^^^^^^^^^^^^^^^^^^~!!!!!!J@@@Y??????????\n");
    printf("~~!JJJPGGGGGG?~~~~~~~~~~~~~JBGGGGGG555J??????7!!!\n");
    printf("~~~~~^G@@@@@@577777777777775@@@@@@B??????????!~~~\n");
    printf("~~~~~~!!!!!!!P@&&&&&&&&&&&@GJJJJJJJ??????????!~~~\n");
    printf("~~~~~~~~~~~~^YBGGBBBBBBBBBBP??????????????777!~~~\n");
    printf("~~~~~~~~~~~~~~~~~????????????????????????7~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~!!!7?????????????7!!!!!!!~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~!?????????????7~~~~~~~~~~~~~~\n");

    usleep(100000);
    system("clear");

    printf("~~~~~~~~~~~~~~~^!&@@@@@&!^~~~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~!???????GGGGGGGJ??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~^^7@@@@@@&.     .&@@@@@@7^~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~YPP5??????7:::::::JYYY555PPPY777~~~~~~~~~~~~\n");
    printf("~~~~~~G@@#       ^^^^^^^^^^~!!!#@@#???!~~~~~~~~~~~~\n");
    printf("~~~~~^G@@#   :^^^:::::::^^^~!!7#@@B??????7~~~~~~~\n");
    printf("~~!???5GG5...:^^^...^7!!^^^~!!!GBBGYYYJ??7~~~~~~~~\n");
    printf("~~?@@@!   ^^^:::.   J@@@^.::^^^!!!Y@@@Y??7~~~~~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??7~~~~~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??7~~~~~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?@@@!  .^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?@@@!   ^^^:::.   J@@&^.::^^^!!!Y@@@Y??????!~~~~~\n");
    printf("~~?&&@7 ..^^^:::.   J@&#^:::^^^777Y@@@Y??????!~~~~~\n");
    printf("~~~!!!P&&B^^^::::...:^^^^^^~!!!B&&BJJJ???????!~~~~~\n");
    printf("~~~~~^G@@#^^^^::::::::::~~~~!!!#@@B??????????!~~~~~\n");
    printf("~~~~~~G@@#^^^^^^^^^^^^^^!!!!!!!#@@B??????????!~~~~~\n");
    printf("~~~~~~?JJYPGGGGGP!~~~~~!PGGGGGGP55Y???????!!!~~~~~~\n");
    printf("~~~~~~~~^7&@@@@@&?77777?&@@@@@@J?????????7~~~~~~~~~\n");
    printf("~~~~~~~~~~!!!!!!7&@&&&&&YJJJJJJ??????????7~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!GGGBBBBJ?????????????7777~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~^!?????????????????!~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~!!!!???????!!!!!!!~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~~~~~???????~~~~~~~~~~~~~~~~~~~~~\n");

    usleep(100000);
    system("clear");

    printf("~~~~~~~~~~~~~~~^!&@@@@@&!^~~~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~7???GGGGGGGJ??7~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~^P@@&.     .&@@P^~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~!PPPY??7:::::::Y555PPP?77!~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@7   ^^^^^^^!!~5@@@Y??7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~^7@@@?   :::::::!7!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~7??JGGG!......^7!!!!~J#BB5Y5Y???!~~~~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@@!^^~!!!#@@B???!~~~~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B???!~~~~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B???!~~~~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@@!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B...:^^^   J@&&!^^~777#@@B??????7~~~~~~~\n");
    printf("~~~~~~!!!?##&J^^^:..:^^^!!!Y&&&YJJJ??????7~~~~~~~\n");
    printf("~~~~~~~~~7@@@Y^^^:::::::!!!5@@@Y?????????7~~~~~~~\n");
    printf("~~~~~~~~~7@@@J:^^^^^^^^^!!!5@@@Y?????????7~~~~~~~\n");
    printf("~~~~~~~~~!JJJ5GGP!~~~~~!PGGG555J??????7!!!~~~~~~~\n");
    printf("~~~~~~~~~~~~^P@@&?77777?&@@G7?????????!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~!!!7&@&&&&&YJJJ??????????!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!GGGBBBBJ??????????777!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~^!?????????????7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~!!!!???????!!!!~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~~~~~???????~~~~~~~~~~~~~~~~~~~\n");

    usleep(100000);
    system("clear");

    printf("~~~~~~~~~~~~~~~~!#&&&&&&!~~~~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@!~~~~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@&!~~~~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@?777777~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!&@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!@@@@@@@J??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!GGGGGGGJ??????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~~~~~???????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~~~~~???????!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~~~~~???????!~~~~~~~~~~~~~~~~~\n");

    usleep(100000);
    system("clear");

    printf("~~~~~~~~~~~~~~~^!&@@@@@&!^~~~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~7???GGGGGGGJ??7~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~P@@#.     .#@@P^~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~P@@&^:::::^#@@G!77~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~P@@&~^^^^^~&@@B???!~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~^P@@&^:::::^&@@B7?????7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~!???5GGP::::::^GBBGYYYJ??7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@?   ::::^^^!!!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~7&&@? ..::::^^^7775@@&Y??????!~~~~~~~~~~\n");
    printf("~~~~~~~~~~!!!P&&B:::::::B&&GJJJ???????!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~^P@@&^:::::^&@@B??????????!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~P@@&~^^^^^~&@@G??????????!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~P@@&!~~~~~!&@@B??????7!!!~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~P@&#?77777?#@@G??????7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~!!!7&@&&&&&YJJJ??????7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!GGGBBBBJ?????????7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~^!?????????????7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~!!!!???????!!!!~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~~~~~???????~~~~~~~~~~~~~~~~~~\n");

    usleep(100000);
    system("clear");

    printf("~~~~~~~~~~~~~~~^!&@@@@@&!^~~~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~7???GGGGGGGJ??7~~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~^P@@&.     .&@@P^~~~~~~~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~!PPPY??7:::::::Y555PPP?77!~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~7@@@7   ^^^^^^^!!~5@@@Y??7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~^7@@@?   :::::::!7!5@@@Y??????!~~~~~~~~~~\n");
    printf("~~~~~~7??JGGG!......^7!!!!~J#BB5Y5Y???!~~~~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@@!^^~!!!#@@B???!~~~~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B???!~~~~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B???!~~~~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@&!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B   :^^^   J@@@!^^~!!!#@@B??????7~~~~~~~\n");
    printf("~~~~~~G@@B...:^^^   J@&&!^^~777#@@B??????7~~~~~~~\n");
    printf("~~~~~~!!!?##&J^^^:..:^^^!!!Y&&&YJJJ??????7~~~~~~~\n");
    printf("~~~~~~~~~7@@@Y^^^:::::::!!!5@@@Y?????????7~~~~~~~\n");
    printf("~~~~~~~~~7@@@J:^^^^^^^^^!!!5@@@Y?????????7~~~~~~~\n");
    printf("~~~~~~~~~!JJJ5GGP!~~~~~!PGGG555J??????7!!!~~~~~~~\n");
    printf("~~~~~~~~~~~~^P@@&?77777?&@@G7?????????!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~!!!7&@&&&&&YJJJ??????????!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~!GGGBBBBJ??????????777!~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~^!?????????????7~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~!!!!???????!!!!~~~~~~~~~~~~~~\n");
    printf("~~~~~~~~~~~~~~~~~~~~~~~~???????~~~~~~~~~~~~~~~~~~\n");}

    usleep(100000);
    system("clear");

  }

}